### ISSUE TITLE
Find a Workaround for oAuth pop-up within Google module

### ISSUE THREAD

**Issue by Usagi629** [Unallocated/EventsAPI#7]
See if there is a way to persist the oAuth token across sessions to avoid the login pop-up, and implement.

**Comment by magikid** [comment]
I found a way to do this in the [API docs](https://developers.google.com/api-client-library/python/guide/aaa_oauth#storage):

    from oauth2client.file import Storage
    ...
    storage = Storage('a_credentials_file')
    storage.put(credentials)
    ...
    credentials = storage.get()
